"use client";

import { useEffect, useMemo, useRef, useState } from "react";

interface GrantEditorProps {
  content: string;
  onChange: (content: string) => void;
  activeSection?: string;
  highlightedText?: { start: number; end: number; color: string };
}

export function GrantEditor({
  content,
  onChange,
  activeSection,
  highlightedText,
}: GrantEditorProps) {
  const [documentTitle, setDocumentTitle] = useState("Untitled Grant Proposal");
  const [documentSubtitle, setDocumentSubtitle] = useState(
    "Draft in progress"
  );
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  // Calculate word count
  const wordCount = useMemo(() => {
    const text = content.trim();
    if (!text) return 0;
    return text.split(/\s+/).filter((word) => word.length > 0).length;
  }, [content]);

  // Calculate character count
  const charCount = useMemo(() => {
    return content.length;
  }, [content]);

  // Auto-resize textarea
  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  }, [content]);

  // Apply highlight to selected range (visual indication only)
  const getHighlightedContent = () => {
    if (!highlightedText) return null;

    const before = content.slice(0, highlightedText.start);
    const highlighted = content.slice(highlightedText.start, highlightedText.end);
    const after = content.slice(highlightedText.end);

    return { before, highlighted, after };
  };

  return (
    <div className="bg-slate-900/50 rounded-xl p-8 min-h-[600px] flex flex-col">
      {/* Document Header */}
      <div className="mb-6 pb-6 border-b border-slate-700">
        <input
          type="text"
          value={documentTitle}
          onChange={(e) => setDocumentTitle(e.target.value)}
          className="w-full text-2xl font-bold text-slate-100 bg-transparent border-none focus:outline-none focus:ring-0 placeholder-slate-500 mb-2"
          placeholder="Enter proposal title..."
        />
        <input
          type="text"
          value={documentSubtitle}
          onChange={(e) => setDocumentSubtitle(e.target.value)}
          className="w-full text-slate-400 bg-transparent border-none focus:outline-none focus:ring-0 placeholder-slate-500"
          placeholder="Add a subtitle..."
        />
      </div>

      {/* Active Section Indicator */}
      {activeSection && (
        <div className="mb-4 px-4 py-2 bg-blue-900/20 border-l-4 border-blue-500 rounded">
          <span className="text-sm text-blue-300">
            Editing: <span className="font-medium">{activeSection}</span>
          </span>
        </div>
      )}

      {/* Main Content Area */}
      <div className="flex-1 relative">
        {highlightedText && (
          <div className="absolute inset-0 pointer-events-none">
            {/* This is a visual overlay for highlighted text */}
            <div className="h-full overflow-hidden text-slate-300 leading-relaxed whitespace-pre-wrap break-words opacity-50">
              {(() => {
                const parts = getHighlightedContent();
                if (!parts) return null;
                return (
                  <>
                    <span className="invisible">{parts.before}</span>
                    <span className="bg-blue-500/20 border-l-2 border-blue-500 pl-4 inline">
                      {parts.highlighted}
                    </span>
                    <span className="invisible">{parts.after}</span>
                  </>
                );
              })()}
            </div>
          </div>
        )}

        <textarea
          ref={textareaRef}
          value={content}
          onChange={(e) => onChange(e.target.value)}
          className="w-full h-full min-h-[400px] bg-transparent text-slate-300 leading-relaxed resize-none focus:outline-none placeholder-slate-500 font-normal"
          placeholder="Start writing your proposal here. Use the AI tools to get suggestions and improvements..."
          style={{
            lineHeight: "1.8",
          }}
        />
      </div>

      {/* AI-Generated Text Note */}
      {highlightedText && (
        <div className="mt-4 px-4 py-3 bg-blue-500/10 border border-blue-500/30 rounded-lg">
          <p className="text-sm text-blue-300">
            <span className="font-medium">AI-Generated Content:</span> Text
            highlighted in blue was generated by AI. Review and edit as needed.
          </p>
        </div>
      )}

      {/* Stats Footer */}
      <div className="mt-6 pt-4 border-t border-slate-700 flex items-center justify-between text-sm">
        <div className="flex items-center gap-6">
          <div>
            <span className="text-slate-400">Words: </span>
            <span className="text-slate-200 font-medium">{wordCount}</span>
          </div>
          <div>
            <span className="text-slate-400">Characters: </span>
            <span className="text-slate-200 font-medium">{charCount}</span>
          </div>
        </div>

        <div className="text-slate-500 text-xs">
          Last edited: {new Date().toLocaleTimeString()}
        </div>
      </div>
    </div>
  );
}
